# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20171112_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
