# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_week_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardsquare',
            options={'ordering': ('-week__start',)},
        ),
    ]
