# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20171114_0439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('-week__start',)},
        ),
        migrations.AlterModelOptions(
            name='cardsquare',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='card',
            order_with_respect_to=None,
        ),
    ]
